// Bundle the headless core for the Python SDK: node scripts/build-core.mjs → ../python/molsketch/_core.js
import { build } from 'esbuild'; import path from 'path'; import { fileURLToPath } from 'url';
const here = path.dirname(fileURLToPath(import.meta.url));
await build({ entryPoints: [path.join(here, '../src/headless/entry.ts')], bundle: true, format: 'iife', target: 'es2020', platform: 'neutral',
  outfile: path.join(here, '../../python/molsketch/_core.js'), legalComments: 'none', logLevel: 'warning',
  banner: { js: '/* MolSketch headless core: generated by app/scripts/build-core.mjs from app/src; do not edit */' } });
console.log('core → python/molsketch/_core.js');
